apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: nginx
spec:
  maxReplicas: 10 # 最大扩容副本量
  minReplicas: 2  # 最小缩容副本量
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 60 # 当整体的资源利用率超过 60%，会进行扩容
status:
  currentReplicas: 0
  desiredReplicas: 0